# Source: nzbget/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  labels:
    app.kubernetes.io/name: nzbget
    helm.sh/chart: nzbget-3.2.0
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6789
      protocol: TCP
      targetPort: http

  selector:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
---
# Source: nzbget/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app.kubernetes.io/name: nzbget
    helm.sh/chart: nzbget-3.2.0
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
      app.kubernetes.io/instance: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/instance: nzbget
    spec:
      containers:
        - name: nzbget
          image: "linuxserver/nzbget:v21.0-ls14"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6789
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: TZ
              value: "Europe/London"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          volumeMounts:
            - mountPath: /config
              name: media-volume
              subPath: configs/nzbget
            - mountPath: /downloads
              name: media-volume
              subPath: library
            - mountPath: /incoming/tv
              name: media-volume
              subPath: downloads/tv
            - mountPath: /incoming/movies
              name: media-volume
              subPath: downloads/movies
          resources:
            {}
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume
