apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: komga
  name: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: komga
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: komga
    spec:
      containers:
      - image: gotson/komga
        imagePullPolicy: "IfNotPresent"
        name: komga
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: media-volume
        - mountPath: /books
          name: komga-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume
status: {}
