# Source: bazarr/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    helm.sh/chart: bazarr-1.0.0
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6767
      protocol: TCP
      targetPort: http

  selector:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
---
# Source: bazarr/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    helm.sh/chart: bazarr-1.0.0
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
        app.kubernetes.io/instance: bazarr
    spec:
      containers:
        - name: bazarr
          image: "linuxserver/bazarr:v0.8.4.2-ls72"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: TZ
              value: "UTC"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          volumeMounts:
            - mountPath: /config
              subPath: configs/bazarr
              name: media-volume
            - mountPath: /tv
              name: media-volume
            - mountPath: /movies
              name: media-volume
          resources:
            {}
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume