---
# Source: metallb/templates/controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  labels:
    heritage: "Helm"
    release: "metallb"
    chart: metallb-0.12.0
    app: metallb
    component: controller
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metallb
      component: controller
      release: "metallb"
  template:
    metadata:
      labels:
        heritage: "Helm"
        release: "metallb"
        chart: metallb-0.12.0
        app: metallb
        component: controller
    spec:
      serviceAccountName: metallb-controller
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: controller
        image: metallb/controller:v0.8.1
        imagePullPolicy: IfNotPresent
        args:
        - --port=7472
        - --config=metallb
        ports:
        - name: monitoring
          containerPort: 7472
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
