---
# Source: metallb/templates/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  labels:
    heritage: "Helm"
    release: "metallb"
    chart: metallb-0.12.0
    app: metallb
---
# Source: metallb/templates/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  labels:
    heritage: "Helm"
    release: "metallb"
    chart: metallb-0.12.0
    app: metallb