name: buildx

on:
  push:
    branches:
      - master
    paths:
        - 'docker/**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - name: Publish changed images
        uses: dawidd6/action-docker-publish-changed@v2
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME}}
          docker_password: ${{ secrets.DOCKER_PASSWORD}}
          github_token: ${{secrets.GITHUB_TOKEN}}
          platforms: linux/amd64,linux/arm64,linux/arm
          tag: latest